### ISSUE TITLE
Beginnend mit ili2fme-6.1.5-20161102: Topic-Filter arbeitet nicht wie erwartet

### ISSUE THREAD

**Issue by behrm** [claeis/ili2fme#1]
Trotz Parametrisierung des Topic-Filters werden für alle (=ungefiltert) zu importierenden Interlis-Entitäten Polygone (wo vorhanden) gebaut und geprüft. Das Verhalten tritt erstmals mit FME2017 auf.

**Comment by claeis** [comment]
TODO: Filterung von ili2fme in die diversen IoxReader verschieben
