### ISSUE TITLE
Workbench created with FME2016/ili2fme-5.8.0-20131209 is not compatibel with newest ili2fme-7.0.3-20190906

### ISSUE THREAD

**Issue by behrm** [claeis/ili2fme#12]
Older FME-Workbenches from FME2016 with  plugin  ili2fme-5.8.0-20131209 and Skip Polygon Building "Yes" have Reader-Objects with postfix "_LT" and "_MT".

FME2019 with newest plugin ili2fme-7.0.3-20190906 opening a "legacy" workbench does read interlis objects (as shown in the log) but the Reader-Objects with postfix "_LT" and "_MT" do not receive any data.

**Comment by claeis** [comment]
That was intentional changed, and one of the reasons for the new major version. The idea is to have the feature types named like in the ili-file ("Polygon" mode) or like in the itf-file ("Raw" mode)
