### ISSUE TITLE
ILI2.4 - LIST/BAG mit primitiven Typen (nicht nur mit Strukturen)

### ISSUE THREAD

**Issue by beistehen** [claeis/ili2fme#20]
Having an attrtibute like this:
`attr1 : LIST {0 .. *} OF TEXT*30;`

According to the reference manual, this INTERLIS LIST has to be encoded like this:
```
<attr1>value A</attr1>
<attr1>value B</attr1>
<attr1>value C</attr1>
...
```

Is there a (simple) way to prepare the data in FME to get the expected output (similar to INTERLIS STRUCTUREs)?

**Comment by beistehen** [comment]
.@olivergrimm any experience with this issue?

**Comment by olivergrimm** [comment]
Vorgesehene Abgrenzung bzgl. Geometrie-Typen:
#https://github.com/claeis/ili2db/issues/471
