### ISSUE TITLE
reader: lookup models in version matching the xtf file version

### ISSUE THREAD

**Issue by claeis** [claeis/ili2fme#22]
should not try to find 2.4 models if reading a 2.3 xtf file

**Comment by peterschaer** [comment]
Is there any known workaround for this problem?

**Comment by claeis** [comment]
ist das in der aktuellen ili2fme Version 7.0.6 immer noch so? https://www.interlis.ch/downloads/ili2fme

**Comment by claeis** [comment]
Workaround: beim ili2fme Parameter Models den Modellnamen explizit setzen

**Comment by peterschaer** [comment]
In 7.0.16 ist das Verhalten noch gleich. Der Workaround funktioniert in 7.0.16 und in 7.0.13. Das reicht in unserem Fall aus. Merci für die prompte Antwort!
