### ISSUE TITLE
ILI2.4 - generischer Koordinaten-Wertebereiche (LV03- oder LV95-Koordinaten)

### ISSUE THREAD

**Issue by claeis** [claeis/ili2fme#26]

**Comment by olivergrimm** [comment]
Nach Rücksprache mit Claude:
> Das Minimum dass man hier m.E. machen müsste ist, den Wert vom "domains" aus dem StartBasketEvent im XTF_BASKETS Feature beim Lesen zu setzen, bzw. beim Schreiben auf dem StartBasketEvent zu setzten.
