### ISSUE TITLE
ili2fme 6.2.1, Interlis Views, Geometrieattribut

### ISSUE THREAD

**Issue by aviquerat** [claeis/ili2fme#3]
Ein Geometrieattribut einer Interlis View muss in dem ILI explizit definiert sein. 
Zum Beispiel : Verlauf : Base.Polyline := base->Verlauf;

Verlauf := base->Verlauf;
ist nicht von ili2fme als Geometrieattribut erkennt, trotzdem das Attribut in dem Base Feature Class als Geometrie definiert ist.

**Comment by claeis** [comment]
fixed in 6.2.2
