### ISSUE TITLE
reading model that contains a VIEW generates NPE

### ISSUE THREAD

**Issue by beistehen** [claeis/ili2fme#35]
Wird ein Reader erstellt, der auf einem Modell basiert, welches eine VIEW enthält, so wird die Auswahlliste der Klassen ("Select Feature Types") nicht angezeigt und im Log erscheint folgende NPE:

```
ilifile <C:\<snip>\poc_view_ili2fme.ili>
java.lang.NullPointerException
java.lang.NullPointerException
	at ch.interlis.ili2fme.Ili2Reader.mapAttributeDef(Ili2Reader.java:1940)
	at ch.interlis.ili2fme.Ili2Reader.mapFeatureType(Ili2Reader.java:1855)
	at ch.interlis.ili2fme.Ili2Reader.myreadSchema(Ili2Reader.java:1703)
	at ch.interlis.ili2fme.Ili2Reader.readSchema(Ili2Reader.java:1590)
```

Environment
```
ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
java.version 1.8.0_265
```

Von diesem Bug sind z. B. alle aktuellen SIA-Modelle betroffen, da sie alle VIEW TOPICS enthalten.

[Beispielmodell: poc_view_ili2fme.ili.txt](https://github.com/claeis/ili2fme/files/11685358/poc_view_ili2fme.ili.txt)

**Comment by olivergrimm** [comment]
Ist reproduzierbar auf unserer Testumgebung. ili2fme-7.0.16 funktionierte noch problemlos.

**Comment by beistehen** [comment]
Ist weiterhin reproduzierbar mit ili2fme-7.3.0.

```
ili2fme-7.3.0-249156fa498b7589c46cdaae7f80d6ecbb22a2e2
ili2c-5.5.1-d1f953308567ccfe0f3b545d33d6f4db0cc25297
iox-ili-1.23.0-d2d939908fc98cb9ad1750fd1007e11cbb0cd9ad
java.version 1.8.0_265
```
