### ISSUE TITLE
ILI2.4 - MultiLine

### ISSUE THREAD

**Issue by dsollb** [claeis/ili2fme#36]
Bei der Umsetzung einer einzelnen Linie erhalte ich folgende Fehlermeldung 
![image](https://github.com/claeis/ili2fme/assets/105778140/92b9d225-3b1b-4b7b-a20a-dd884624d48d)

**Comment by beistehen** [comment]
Aus dem Screenshot ist nicht ersichtlich, welche ili2fme-Version du einsetzt. Die aktuellste Version ist 7.2.1, welche viele Neuerungen betreffend die Unterstützung von ILI2.4 erfahren hat. Du kannst sie [hier](https://downloads.interlis.ch/ili2fme/) herunterladen.

Installationsanleitung gibt es [hier](http://ili2fme.ch/reference#how-to-migrateupdate-an-existing-ili2fme-installation).

**Comment by dsollb** [comment]
Ich hab die Version 7.2.1 im Einsatz.
Das Problem habe ich bei mir Vorort mit Claude Eisenhut angeschaut.
Das Problembesteht darin dass MuliLine nicht alle Elementtypen unterstützt.
Im konkreten Fall fehlt der IFMELine Typ.
