### ISSUE TITLE
ILI2FME Interlis 2.4

### ISSUE THREAD

**Issue by Geoverm** [claeis/ili2fme#39]
Beim Export der Daten in ein XTF INTERLIS 2.4 werden die Geometrien welche Kreisbögen enthalten und in einer STRUCTURE ausgegeben werden sollen, nicht wunschgemäss exportiert. Sobald Kreisbögen betroffen sind, wird die Geometrie verformt.

Parameter für den Export:
![Parameter FME2ILI](https://github.com/claeis/ili2fme/assets/118368574/0382daf5-6a3e-4dba-b8f8-7272ed1e1e65)

ILI-Modell (Beispiel):
![Auszug DMAV](https://github.com/claeis/ili2fme/assets/118368574/0243e653-b985-4afb-9fc9-71a1395460b1)

**Comment by claeis** [comment]
Das Problem ist die Einstellung "OGC Well Known Binary". Weil damit die Radien irgendwie/undokumentiert/unspezifiziert codiert werden. Mit FMEBIN geht es. Siehe Anhang 
[polygoninstruct.zip](https://github.com/claeis/ili2fme/files/14509358/polygoninstruct.zip)
