### ISSUE TITLE
Polygon Building mit Interlis1

### ISSUE THREAD

**Issue by ech-mauh** [claeis/ili2fme#4]
Die angefügte Interlis1-Datei soll aufgrund von Kleinstüberlappungen durch den FME-Transformer «Matcher» bearbeitet werden.
[export_2018_08_21.zip](https://github.com/claeis/ili2fme/files/2318173/export_2018_08_21.zip)

Mit dem in FME 2018 standardmässig installierten FME-Plugin bricht der Prozess mit Fehlermeldungen ab, ausser das Polygon-Building ist deaktiviert, aber dann werden nicht alle Features gelesen.
Wenn mit FME 2018 ein altes FME-Plugin verwendet wird (ili2fme-5.8.0), kann die itf-Datei erfolgreich eingelesen und bearbeitet werden.

**Comment by ech-mauh** [comment]
Are there any news to this issue?

**Comment by claeis** [comment]
Sollte mit der neusten Version ili2fme-6.3.0 funktionieren.

**Comment by ech-mauh** [comment]
nun erhalte ich die Fehlermeldung: tried to access field com.vividsolutions.jts.geom.LineString.points from class ch.interlis.iom_j.itf.impl.jtsext.geom.CompoundCurveRing
Was bedeutet diese Meldung?

**Comment by claeis** [comment]
Im Folder

    $FME/plugins/

ist die Datei jts-1.8.jar im Konflikt mit jts-core-1.14.0.jar

Also jts-1.8.jar entfernen, dann sollte es gehen.

**Comment by ech-mauh** [comment]
Dies führt mich zum nächsten Fehler:

XTF_ERRORS: qualified INTERLIS name expected instead of <XTF_ERRORS>
ch.interlis.ili2fme.ConfigException: XTF_ERRORS: qualified INTERLIS name expected instead of <XTF_ERRORS>
ch.interlis.ili2fme.ConfigException: XTF_ERRORS: qualified INTERLIS name expected instead of <XTF_ERRORS>
Destination Feature Type Routing Correlator (RoutingFactory): ch.interlis.ili2fme.ConfigException: XTF_ERRORS: qualified INTERLIS name expected instead of <XTF_ERRORS>

**Comment by claeis** [comment]
Wo ist das ili Modell?

**Comment by ech-mauh** [comment]
imselben Verzeichnis wie die itf-Datei. Selbst wenn ich den Pfad auf den Parameter "Models directory" explizit setze, erhalte ich dieselbe Fehlermeldung.

**Comment by claeis** [comment]
XTF_ERRORS sind Fehlermeldungen des Interlis Readers als FME Features und können ignoriert oder gelooged oder wie auch immer verarbeitet werden. Und sollten aber nicht als Feature dem Interlis Writer übergeben werden (das führt zu obiger Fehlermeldung).

**Comment by claeis** [comment]
Bitte das ili-Modell dem issue anhängen

**Comment by ech-mauh** [comment]
[Nutzungsplanung_LU_200_LV95.zip](https://github.com/claeis/ili2fme/files/3166996/Nutzungsplanung_LU_200_LV95.zip)

**Comment by claeis** [comment]
Die itf Datei enthlät doppelte Linien bei Grundnutzung_Geometrie, z.B. 1000 und 2288; und ist somit fehlerhaft.

**Comment by ech-mauh** [comment]
Wir exportieren eine Interlisdatei aus einer FileGeodatabase mit FME. Die FileGeodatabase enthält keine doppelten Linien bei der Grundnutzung. Die Interlisdatei enthält nach dem Export doppelte Linien, weshalb wir bis anhin mit dem Matcher gearbeitet haben. Dies funktioniert nun nicht mehr. Beim Lesen der exportieren Interlisdatei folgt die Meldung wie oben erwähnt.

**Comment by claeis** [comment]
Dieses Issue trägt den Titel "Polygon Building..." und enthält ITF-Daten. Es geht somit um ein Problem beim Reader. Wenn jetzt der Verdacht ist, dass es beim Writer ein Problem gibt, bitte dafür ein neues Issue erstellen, und da dann bitte  minimale Daten und Workbench anhängen, die das Problem reproduzieren.

**Comment by ech-mauh** [comment]
Es geht tatsächlich um ein Reader-Problem. In einer früheren Version (2017?), konnte ich itf-Daten mit kleinsten Überlappungen einlesen (Check Polygon Building: No / Skip Polygon Building: No) und mit einem Matcher verarbeiten. Mit der Version 2019 werden diese Objekte mit kleinsten Überlappungen jedoch gar nicht mehr gelesen, sondern landen in xtf_errors und können deshalb nicht mehr verwendet werden.
[Import_FME_2019.zip](https://github.com/claeis/ili2fme/files/3183188/Import_FME_2019.zip)

**Comment by claeis** [comment]
Die Daten sollten nach Möglichkeit bei der Quelle korrigiert werden. (Um solche Daten via FME zu bereinigen, würde ich die Polygonbildung von ili2fme ausschalten)

**Comment by ech-mauh** [comment]
Wenn ich das Polygon-Building ausschalte, dann werden diejenigen Objekte mit Kleinstüberlappungen mit ili2fme nicht mehr eingelesen und ich kann sie dadurch mit dem Matcher nicht bereinigen. Bis anhin hat dieser Vorgang funktioniert.

**Comment by ech-mauh** [comment]
Gibt es Neuigkeiten zu diesem Issue?

**Comment by claeis** [comment]
Wie schon gesagt: mit ausgeschalteter Polygonbildung kann man die Daten lesen, und in der Workbench bereinigen. Mit welchen Transformern man das macht, ist eine FME Frage und keine ili2fme Frage, und darum hier der falsche Ort.

**Comment by claeis** [comment]
[fixpolygons.zip](https://github.com/claeis/ili2fme/files/3206243/fixpolygons.zip)
