### ISSUE TITLE
Error adding reader with 'SIA405_FERNWAERME_2015_LV95' model

### ISSUE THREAD

**Issue by raketwo** [claeis/ili2fme#40]
Beim Versuch, einen Interlis2 Datensatz mit dem angehängten Modell SIA405_FERNWAERME_2015_LV95 und einem Reader einzulesen, erscheint u.a. folgende Fehlermeldung.

> Cannot invoke "ch.interlis.ili2c.metamodel.Type.getCardinality()" because the return value > of "ch.interlis.ili2c.metamodel.AttributeDef.getDomain()" is null

Bedeutung und Lösung des Problems?

gemäss erster Auskunft liegt ein Problem mit dem Modell vor, nicht mit dem (Test-)Datensatz. Diesen kann ich leider ohnehin nicht verlinken.

 ### Environment
```sh
ili2fme version=7.2.0 versionCommit=ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c 5.0.9-20200401
FME Workbench 2023.2
SIA405_FERNWAERME_2015_LV95
```

![image](https://github.com/claeis/ili2fme/assets/151773277/b157980a-6cbd-4759-b80f-e3b10af67c25)

**Comment by beistehen** [comment]
> ili2fme version=7.2.0 versionCommit=ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c 5.0.9-20200401

Was mir als Erstes auffällt ist die uralte Version von ili2c (v5.0.9). Diese passt so gar nicht zur Version, die mit ili2fme v7.2.0 ausgeliefert wird. Es bestehen Abhängigkeiten zwischen den einzelnen Software-Werkzeugen.

Ich würde dir empfehlen, ili2fme neu zu installieren (Download [Version 7.2.0](https://downloads.interlis.ch/ili2fme/ili2fme-7.2.0.msi), [aktuellste Version 7.3.0](https://downloads.interlis.ch/ili2fme/ili2fme-7.3.0.msi)) und zu schauen, ob das Problem weiterhin besteht.

PS. Das offizielle Fernwärme-Modell im [SIA-Repository](https://405.sia.ch/models/2015/) ist fehlerfrei. Falls deine Modell-Version nicht manuell abgeändert wurde, sollte sie also ebenfalls gültig sein.

**Comment by raketwo** [comment]
> Ich muss mich korrigieren. Wegen Issue https://github.com/claeis/ili2fme/issues/35 musst du zudem folgendes modifiziertes
> Modell verwenden, damit es funktioniert. Eine sauber installierte ili2fme-Version würde ich trotzdem als Basis empfehlen.

> [SIA405_Fernwaerme_2015_2_d-20180426_noView.ili.txt]
> (https://github.com/claeis/ili2fme/files/14747009/SIA405_Fernwaerme_2015_2_d-20180426_noView.ili.txt) (Endung nach dem
> Download wieder umwandeln in .ili)

Mit dem modifizierten Modell hat es nun geklappt!
