### ISSUE TITLE
Problem Daten aus Interlis2-Modell in FME importieren

### ISSUE THREAD

**Issue by ZiReKost** [claeis/ili2fme#42]
Ich kann die Interlis2-Daten aus surs_was.XTF (brauche eigentlich nur Tabelle SIA405_WASSER_2015_LV95.SIA405_Wasser.Hydrant) nicht in FME importieren.
Ich habe den Pfad für ILI-Daten erweitert, es sollten keine Modell-Daten fehlen, geht aber nicht…, bekomme mit FME 2023 Fehlermeldungen und mit FME 2021 sehe ich die Tabelle ‘Hydranten’ nicht.
Eigentlich möchte ich aus der Tabelle Hydranten nur eine Excelliste generieren.

Vermutlich ist das Problem gelöst mit der aktuellen Version 7.3.1. von ili2fme.
https://www.interlis.ch/downloads/ili2fme
> Habe ich bereits gemacht...

Log FME:
Starting translation...
                FME 2023.1.1.0 (20230928 - Build 23631 - WIN64)
                              FME Form (floating)
                               Permanent License.
                        Machine host name is: KOSTNB113
          Operating System: Microsoft Windows 11 64-bit  (Build 22631)
                 Copyright (c) 1994 - 2023, Safe Software Inc.
                               Safe Software Inc.
Current FME version: FME 2023.1.1.0 (20230928 - Build 23631 - WIN64)
System Time: 20240429085406 UTC
FME_HOME is 'C:\Program Files\FME\'
FME Form (floating)
Permanent License.
Machine host name is: KOSTNB113
OS Locale Name     : de_CH
OS Locale Encoding : windows-1252
Process Encoding   : UTF-8
FME API version: '4.0 20230426'
FME Configuration: FME_BASE is 'no'
Operating System: Microsoft Windows 11 64-bit  (Build 22631)
FME Platform: WIN64
System Status: 708.23 GB of disk space available in the FME temporary folder (C:\Users\RETO~1.ZIS\AppData\Local\Temp\wbrun_1714380832845_23240\fmetmp_0)
System Status: 31.67 GB of physical memory available
System Status: 126.69 GB of virtual memory available
START - ProcessID: 21944, peak process memory usage: 42184 kB, current process memory usage: 42176 kB
Creating reader for format: Swiss INTERLIS (ili2fme)
Trying to find a JAVA plugin for reader named `ch.ehi.fme.Main'
Attempting to load Java Virtual Machine from C:\Program Files\FME\jre\bin\server
ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
java.version 17.0.8
maxMemory 8302592 KB
ili2fme reader uses enhanced geometry handling
checkUniqueOid <false>
metaConfig <>
validate <true>
validationConfig <>
validateMultiplicity <true>
ili1IgnorePolygonBuildingErrors <false>
trimValues <true>
geometryEncoding <FMEBIN>
geoAttrMapping <EncodeAsFmeAttribute>
ili1RenumberTid <false>
lineTables <Polygon>
inheritanceMapping <SuperClass>
createEnumTypes <No>
ili1AddDefVal <false>
ili1EnumAsItfCode <false>
xtfFile <L:\Auftrag\GEO\Mehrere\21016\08\surs_was.XTF>
modeldir <%XTF_DIR;http://models.interlis.ch/;C:\Program Files\FME/plugins/interlis2/ilimodels;C:\Program Files\FME/plugins/interlis2/ili22models>
modelVersion from xtf <2.3>
model from xtf <SIA405_WASSER_2015_LV95>
lookup model <SIA405_WASSER_2015_LV95> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <SIA405_Base> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <Units> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <Base> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <SIA405_Base_LV95> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <SIA405_Base_LV95> 2.3 in repository <http://models.interlis.ch/>
lookup model <SIA405_Base_LV95> 2.3 in repository <C:\Program Files\FME/plugins/interlis2/ilimodels/>
lookup model <SIA405_Base_LV95> 2.3 in repository <C:\Program Files\FME/plugins/interlis2/ili22models/>
lookup model <SIA405_Base_LV95> 2.3 in repository <http://models.geo.admin.ch/>
lookup model <SIA405_Base_LV95> 2.3 in repository <https://models.kgk-cgc.ch/>
lookup model <SIA405_Base_LV95> 2.3 in repository <https://models.interlis.ch/>
lookup model <SIA405_Base_LV95> 2.3 in repository <https://models.geo.llv.li/>
lookup model <SIA405_Base_LV95> 2.3 in repository <https://405.sia.ch/models/>
lookup model <Base_LV95> 2.3 in repository <L:\Auftrag\GEO\Mehrere\21016\08/>
lookup model <Base_LV95> 2.3 in repository <http://models.interlis.ch/>
lookup model <Base_LV95> 2.3 in repository <C:\Program Files\FME/plugins/interlis2/ilimodels/>
lookup model <Base_LV95> 2.3 in repository <C:\Program Files\FME/plugins/interlis2/ili22models/>
lookup model <Base_LV95> 2.3 in repository <http://models.geo.admin.ch/>
lookup model <Base_LV95> 2.3 in repository <https://models.kgk-cgc.ch/>
lookup model <Base_LV95> 2.3 in repository <https://models.interlis.ch/>
lookup model <Base_LV95> 2.3 in repository <https://models.geo.llv.li/>
lookup model <Base_LV95> 2.3 in repository <https://405.sia.ch/models/>
ilifile <L:\Auftrag\GEO\Mehrere\21016\08\Units.ili>
ilifile <L:\Auftrag\GEO\Mehrere\21016\08\Base.ili>
ilifile <C:\Users\reto.ziswiler\.ilicache\405.sia.ch\models\2015\Base_d-20181005.ili>
ilifile <L:\Auftrag\GEO\Mehrere\21016\08\SIA405_Base.ili>
ilifile <C:\Users\reto.ziswiler\.ilicache\405.sia.ch\models\2015\SIA405_Base_d-20181005.ili>
ilifile <L:\Auftrag\GEO\Mehrere\21016\08\SIA405_WASSER_2015_LV95.ili>
FME Session Duration: 2.7 seconds. (CPU: 0.3s user, 0.2s system)
END - ProcessID: 21944, peak process memory usage: 756516 kB, current process memory usage: 753288 kB
ch.interlis.ili2c.Ili2cFailure: compiler failed
	at ch.interlis.ili2c.Ili2c.runCompiler(Ili2c.java:23)
	at ch.interlis.ili2fme.Ili2Reader.myopen(Ili2Reader.java:571)
	at ch.interlis.ili2fme.Ili2Reader.open(Ili2Reader.java:140)
Failed to obtain any schemas from reader 'ch.ehi.fme.Main' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading. See logfile for more information
Program Terminating
Translation FAILED.

**Comment by beistehen** [comment]
> Habe ich bereits gemacht...

Wenn diese Aussage bedeutet, dass du bereits auf 7.3.1 aktualisiert hast, so ist sie (gemäss Logfile) nicht zutreffend. Dort steht:

`ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42`

Für die SIA-Modelle sollte die Version 7.3.1 verwendet werden.

**Comment by ZiReKost** [comment]
Habe es nun in FME 2023 gemacht:
ili2fme-7.3.1-97152071bc59aa1fddb318d65a4979498a33f8b0

Sehe aber die Tabelle *.Hydranten nicht:
***@***.***

Freundliche Grüsse
Reto Ziswiler

Fachausweis als Vermessungstechniker
Projektleiter
Teamleiter Geoinformatik


***@***.***
KOST + PARTNER AG Ingenieure und Planer
Industriestrasse 14 I 6210 Sursee
***@***.******@***.***>


Direkt 041 926 06 79
041 926 06 06
Besuche uns unter:
www.kost-partner.ch<http://www.kost-partner.ch>

***@***.******@***.******@***.***<https://www.linkedin.com/company/kost-und-partner-ag/>

Von: Stefan Henrich ***@***.***>
Gesendet: Montag, 29. April 2024 11:20
An: claeis/ili2fme ***@***.***>
Cc: Ziswiler Reto ***@***.***>; Author ***@***.***>
Betreff: Re: [claeis/ili2fme] Problem Daten aus Interlis2-Modell in FME importieren (Issue #42)


Habe ich bereits gemacht...

Wenn diese Aussage bedeutet, dass du bereits auf 7.3.1 aktualisiert hast, so ist sie (gemäss Logfile) nicht zutreffend. Dort steht:

ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42

Für die SIA-Modelle sollte die Version 7.3.1 verwendet werden.

**Comment by beistehen** [comment]
> Sehe aber die Tabelle *.Hydranten nicht:

Was bedeutet "nicht sehen"? Erscheint die Tabelle nicht bei der Auswahl der Featuretypen nach dem Hinzufügen des Readers?

Ein Screenshot wäre hilfreich.

**Comment by ZiReKost** [comment]
Genau, die Tabelle  Hydranten wird nicht vorgeschlagen:
***@***.***

Freundliche Grüsse
Reto Ziswiler

Fachausweis als Vermessungstechniker
Projektleiter
Teamleiter Geoinformatik


***@***.***
KOST + PARTNER AG Ingenieure und Planer
Industriestrasse 14 I 6210 Sursee
***@***.******@***.***>


Direkt 041 926 06 79
041 926 06 06
Besuche uns unter:
www.kost-partner.ch<http://www.kost-partner.ch>

***@***.******@***.******@***.***<https://www.linkedin.com/company/kost-und-partner-ag/>

Von: Stefan Henrich ***@***.***>
Gesendet: Montag, 29. April 2024 11:35
An: claeis/ili2fme ***@***.***>
Cc: Ziswiler Reto ***@***.***>; Author ***@***.***>
Betreff: Re: [claeis/ili2fme] Problem Daten aus Interlis2-Modell in FME importieren (Issue #42)


Sehe aber die Tabelle *.Hydranten nicht:

Was bedeutet "nicht sehen"? Erscheint die Tabelle nicht bei der Auswahl der Featuretypen nach dem Hinzufügen des Readers?

Ein Screenshot wäre hilfreich.

**Comment by beistehen** [comment]
> Genau, die Tabelle  Hydranten wird nicht vorgeschlagen:

Dann musst du in den Parametern des Readers die Mapping-Strategie auf *SubClass* umstellen:
![grafik](https://github.com/claeis/ili2fme/assets/26199857/ba4db494-1e06-4f00-8347-6468c1c59d4a)

**Comment by ZiReKost** [comment]
Besten Dank, jetzt sehe ich die Tabelle Hydranten….

Freundliche Grüsse
Reto Ziswiler

Von: Stefan Henrich ***@***.***>
Gesendet: Montag, 29. April 2024 11:48
An: claeis/ili2fme ***@***.***>
Cc: Ziswiler Reto ***@***.***>; Author ***@***.***>
Betreff: Re: [claeis/ili2fme] Problem Daten aus Interlis2-Modell in FME importieren (Issue #42)


Genau, die Tabelle Hydranten wird nicht vorgeschlagen:

Dann musst du in den Parametern des Readers die Mapping-Strategie auf SubClass umstellen:
grafik.png (view on web)<https://github.com/claeis/ili2fme/assets/26199857/ba4db494-1e06-4f00-8347-6468c1c59d4a>

**Comment by ZiReKost** [comment]
Vielen Dank für die Unterstützung…

Freundliche Grüsse
Reto Ziswiler

Fachausweis als Vermessungstechniker
Projektleiter
Teamleiter Geoinformatik


***@***.***
KOST + PARTNER AG Ingenieure und Planer
Industriestrasse 14 I 6210 Sursee
***@***.******@***.***>


Direkt 041 926 06 79
041 926 06 06
Besuche uns unter:
www.kost-partner.ch<http://www.kost-partner.ch>

***@***.******@***.******@***.***<https://www.linkedin.com/company/kost-und-partner-ag/>

Von: Claude Eisenhut ***@***.***>
Gesendet: Dienstag, 30. April 2024 10:12
An: claeis/ili2fme ***@***.***>
Cc: Ziswiler Reto ***@***.***>; Author ***@***.***>
Betreff: Re: [claeis/ili2fme] Problem Daten aus Interlis2-Modell in FME importieren (Issue #42)


Closed #42<https://github.com/claeis/ili2fme/issues/42> as completed.
