### ISSUE TITLE
FME plugin “Swiss INTERLIS (ili2fme) Reader/Writer”: possible bug

### ISSUE THREAD

**Issue by znarf1965** [claeis/ili2fme#7]
I have a very simple itf file where a single object influences geometry interpretation on himself and other objects in the same file.

In file airolo.itf (attached) there are only two geometries.
On executing ITF_GDB.2.fmw I expect two “area” but get two “nulls”.
But if I delete vertex on line 74 (or 72 or 73) and run again ITF_GDB.2.fmw I get two “area” as expected.
It seems that object VeritiID34002 generates a problem on how FME interprets that geometry and other geometries in the same itf file.
But I also have another strange behaviour: if I change tid from “VeritiID34002” to “ch06ty8c001100000” (leaving the rest unchanged) I get first geometry interpreted as “area” (as expected) and the other as “null” (and it shouldn’t).
In that case, changing his tid from “VeritiID34002” to “ch06ty8c001100000”, the second object does not influences interpretation on first one.
 
Have any idea on what’s wrong?...

Best regards

Francesco Sozzi
[fme.interlis.zip](https://github.com/claeis/ili2fme/files/2978554/fme.interlis.zip)
[mails.zip](https://github.com/claeis/ili2fme/files/2978557/mails.zip)

**Comment by claeis** [comment]
The polygon building of SURFACE attributes aborts with the first error (I will change/improve this). And the order of evaluation is influenced by the TID value (I will not change this); therefor the different behavior.

**Comment by claeis** [comment]
fixed in ili2fme-6.3.0
